### ISSUE TITLE
Please update to the latest Diabloweb or point to the upstream

### ISSUE THREAD

**Issue by AJenbo** [Emupedia/emupedia.github.io#11]
https://github.com/Emupedia/emupedia.github.io/blob/61e2b60848bb6ce62feb10e2fe317ada3d2869da/beta/index.html#L36

See https://github.com/d07RiV/diabloweb/issues/137

**Comment by ZaDarkSide** [comment]
Will do, thank you for opening a issue.

**Comment by ZaDarkSide** [comment]
Updated to latest upstream, but multiplayer still won't work because server is down.

**Comment by AJenbo** [comment]
It also doesn´t support Hellfire but I don´t see how that is relevant?

**Comment by ZaDarkSide** [comment]
It's not, but the only updates from upstream are multiplayer related.

**Comment by AJenbo** [comment]
Actually upstream hade the following changes compared to the old version:

- MPQ fixes
- iPhone fixes
- Better error reporting
- MPQ compression
- Remote loading
- Fix cut screen
- Fix Safari audio
- Touch UI
- Save game manager
- Warning on incorrect MPQ
- Fix loading quests in Shareware

Some of thease where the cause of a lot of the error reports we where getting.

**Comment by ZaDarkSide** [comment]
Glad we updated then, didn't know they were so many changes and fixes. Thanks for the heads-up.
