### ISSUE TITLE
GOOD NEWS

### ISSUE THREAD

**Issue by Hoodgail** [Emupedia/emupedia.github.io#14]
yoooo i say ur site on tick with 4.8k likes
because of the games u got on there, 
add more... 
https://vm.tiktok.com/7krkfr/

**Comment by gplastic** [comment]
Well, you don't need to make an issue about this. The site already exploded in popularity thanks to Tik Tok a while back in February. (The 11th i think?) I guess you can call it a symbiotic relationship, eh?
