### ISSUE TITLE
(request) Add Pikachu Volleyball js port

### ISSUE THREAD

**Issue by maurom** [Emupedia/emupedia.github.io#16]
Well, this is more of a wishlist than a request so feel free to dismiss it if it is not relevant.

@gorisanson did a great work porting this old windows game to js

**Pikachu Volleyball**
https://github.com/gorisanson/pikachu-volleyball

Pikachu Volleyball is an old Windows game which was developed in Japan in 1997. The game was popular in Korea when [the port author] was young. 

I don't know if it is known outside Korea, but for sure it did reach South America around that time, too, so it would be a nice addition to this web-based OS.

**Comment by ZaDarkSide** [comment]
Added in EmuOS: https://emupedia.net/beta/emuos/#/emupedia-game-pikachu-volleyball
Direct link: https://emupedia.net/emupedia-game-pikachu-volleyball/
