### ISSUE TITLE
Why does Minecraft have the "Under development" tooltip?

### ISSUE THREAD

**Issue by AndrewL2018** [Emupedia/emupedia.github.io#19]
Is there more that going to be done to modify it to parity a more polished version of Minecraft? Or is it just an oversight and left on the icon by accident?

**Comment by ZaDarkSide** [comment]
Yes, we are working to improve the classic version and add some features from the full game if possible also the ability to play with friends in multiplayer.

**Comment by TheAlienDrew** [comment]
How many more features are we talking here? Getting it to version 1.0? (same person by the way, just my personal github account)

**Comment by ZaDarkSide** [comment]
For starters more block types, but don't expect updates anytime soon.

**Comment by TheAlienDrew** [comment]
Gotcha, well you might want to check out https://repl.it/@modded/classic for some work already done in modding it. Additionally, I was dissected some of the code and resources and documented it a bit at https://github.com/TheAlienDrew/minecraft-classic/blob/master/ASSETS_NOTE.md

**Comment by ZaDarkSide** [comment]
Interesting, but I see other people have no much progress also.
