### ISSUE TITLE
Spammers

### ISSUE THREAD

**Issue by WAGEOFFICIAL** [Emupedia/emupedia.github.io#25]
@ZaDarkSide 
Emu chat is what I use the most on Emupedia and I love it, but lately there has been multiple spammers and I have respectfully asked them to stop spamming, but they seem to not care. All that I'm asking is to add a mod who can ban or a anti-spamming system

**Comment by ZaDarkSide** [comment]
You are right, but we are short on staff, if you want to become a mod, please contact us on [Discord](https://discord.gg/wXtGQ4p)
