### ISSUE TITLE
NSFW warning plz

### ISSUE THREAD

**Issue by okay-cmd** [Emupedia/emupedia.github.io#28]
so people in the casual talk channel on discord keep complaining that it IS NOT KID FRIENDLY and people are spamming, and do not realize that, this channel is unmonitored. I suggest that u add a warning so that people cant bitch about it. i realize that most people on there are just kids on school Chromebooks, so maybe when they join emuOS they do not see the warning? i don't understand it all but I think It is definitely an issue.

**Comment by ZaDarkSide** [comment]
Maybe delete the Discord app altogether from the website is a better choice.

**Comment by ZaDarkSide** [comment]
I have disabled guest mode for now, so you really need to login with a valid Discord account in order to talk.

**Comment by okay-cmd** [comment]
ok thankyou
