### ISSUE TITLE
TikTok people are apparently coming here? somehow?

### ISSUE THREAD

**Issue by BleachyGlicth** [Emupedia/emupedia.github.io#29]
idk but its either just bots coming here that y'all are adding or just tiktok people that are raiding here for some reason which is causing a big user usage in the server, doesn't mean that theres so much lag its just like...why so many? either duplicate of people or just like something else

**Comment by ZaDarkSide** [comment]
Nope just someone made a video or something and the website is suddenly more popular, that's all nothing to worry about. The only thing is the chat server can't cope with so many people at once but we are working on it.
