### ISSUE TITLE
WE ARE BEING HACKED

### ISSUE THREAD

**Issue by BleachyGlicth** [Emupedia/emupedia.github.io#32]
it says "emupedia says: get hacked"  please help ASAP

**Comment by juicywad** [comment]
He said that the sight is vulnerable to xss attacks and that he is cool with anime. lol He said to warn the developers before the page was hacked by someone else.

**Comment by Caitie502** [comment]
They also keep sending/forcing open new tabs of an image of a naked man exposing his prolapsed anus

**Comment by ZaDarkSide** [comment]
The issue has been fixed.
