### ISSUE TITLE
Half-Life problem 

### ISSUE THREAD

**Issue by BlackRev3nger-YT** [Emupedia/emupedia.github.io#37]
On every browser, on pc, my phone, everywhere Half-Life just doesn't load, The white bar never gets colored with blue (meaning its downloading) so I wonder, what is happening exactly? Because I have a feeling that its not downloading or something.

**Comment by ZaDarkSide** [comment]
Yes you are right, the CDN is down, we will fix it, thank you for reporting the issue.

**Comment by ZaDarkSide** [comment]
Issue has been fixed for now.
