### ISSUE TITLE
Trying to update SFA

### ISSUE THREAD

**Issue by gamedev8** [Emupedia/emupedia.github.io#39]
I've made some changes and would like to create a testable branch off of [Emupedia/emupedia-game-street-fighter-alpha](https://github.com/Emupedia/emupedia-game-street-fighter-alpha), but I'm not able to fork since I own [gamedev8/js-sfa](https://github.com/gamedev8/js-sfa). How can I update [Emupedia/emupedia-game-street-fighter-alpha](https://github.com/Emupedia/emupedia-game-street-fighter-alpha) ?

**Comment by ZaDarkSide** [comment]
I can transfer the repo to your ownership and also add me as contributor.

**Comment by gamedev8** [comment]
Can you temporarily add me to the Emupedia org and only give me access to emupedia-game-street-fighter-alpha ?

**Comment by ZaDarkSide** [comment]
Sure go to https://github.com/Emupedia/emupedia-game-street-fighter-alpha/invitations
