### ISSUE TITLE
SFA Dramatic Battles (Request)

### ISSUE THREAD

**Issue by UA106** [Emupedia/emupedia.github.io#5]
Can you remove the Dramatic Battle option as being the default in Street Fighter Alpha? Or some kind of hotkey for toggling the options. Thanks!

**Comment by gamedev8** [comment]
There are 2 ways to do this:

execute the following when it starts up.
``window.game_.setTeamMode(false);``

or update the following line to `false`
https://github.com/gamedev8/js-sfa/blob/master/script/game.js#L59

**Comment by ZaDarkSide** [comment]
@gamedev8 thanks for the hints, can you join our Discord server here https://discord.gg/wXtGQ4p to have a discussion on how we can continue the project and provide a proper game menu?

**Comment by ZaDarkSide** [comment]
Anyway i pushed some changes to that effect here https://github.com/Emupedia/emupedia-game-street-fighter-alpha/commit/c5719519b2a93bd70ed5557d9341c3108b935525#diff-e3f4efbe9f975868bcbac1c372abecf8

**Comment by gamedev8** [comment]
> @gamedev8 thanks for the hints, can you join our Discord server here https://discord.gg/wXtGQ4p to have a discussion on how we can continue the project and provide a proper game menu?

ok I will join
