### ISSUE TITLE
Switch Geometry Dash to use Forkphorus

### ISSUE THREAD

**Issue by gplastic** [Emupedia/emupedia.github.io#6]
Forkphorus (https://forkphorus.github.io/) is a tool that can run Scratch projects in full speed javascript with the added benefit of window scaling and higher framerates with embed support. The scratch embed version of Geometry Dash underperforms on lower end systems like Chromebooks and lacks window scaling. Switching the embed to use Forkphorus may make it into a more playable package.

**Comment by ZaDarkSide** [comment]
I have tried the version compiled by Forkphorus, but it's crashing on first level:
See here: https://forkphorus.github.io/app.html?id=105500895&w=900

**Comment by gplastic** [comment]
Oh, I didn't notice that. That's a shame.

**Comment by gplastic** [comment]
https://forkphorus.github.io/keep-in-view/#356566581

From the forkphorus issue
This should work just fine.
