### ISSUE TITLE
my account

### ISSUE THREAD

**Issue by Isaac0770** [Emupedia/emupedia.github.io#62]
ok please dont ban me when i say this but im th 1 that was in aflacs account, but... its not my fault i didnt know what /recover did and bless told me to enter it but now im stuck in aflacs account i dont know my id to get back and now that u fixed his id i cant get on to even put an id down

**Comment by ZaDarkSide** [comment]
This is not the place to post issues for EmuChat, if you have any questions please join Discord https://discord.gg/wXtGQ4p
